### PR TITLE
Ft/blossom/profile functionality

### PR DESCRIPTION
**Pull request by Blossom1-chike**
### [Please link the Jira ticket that this PR addresses here.]
profile functionality

## Description
[Please put a description of the changes this branch introduces here.]

## To Test
[Please write instructions for testing your changes locally here. Include any data setup, tests, urls, and potential snags in local testing.]

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
[Any screenshots of the changes can go here.]

## Extra Notes
[Please include any extra notes you may have about the changes here.]

### CODE REVIEW

**Comment by Eshy10** [comment]
@Blossom1-chike please fix your merge conflicts

**Comment by Eshy10** [comment]
@Blossom1-chike the initial state for the profile section is prefilled just like the UI on figma .
Screenshot 2023-12-29 at 00 04 06
Screenshot 2023-12-29 at 00 01 49


also, i should be able to edit the cards below please discuss the ux with Samuel or confirm if we don't need it.

Screenshot 2023-12-29 at 00 02 30

**Review by ObiTam — COMMENTED** [review]
Hi @Blossom1-chike ,

This looks really good. I think this profile page is a bit complicated and will be difficult to wireup to the backend. I want to work with you on the modularity and the encapsulation of the profile component and its 2 tabs.

Lets work from there downward to under-complicate it.

1. There should be 2 components for the password and profile tabs. These should be completely seperate. the logic for tab selection should be on the profile component only.
2. Let there be one Object holding all the Store Info, Delivery Fees and Holiday data. This object will serve like an input to the profile page. It will be stored in redux then initialized into a state variable in the component. In essence, when wireup is being done this is the object that will be coming from the backend as input to our function.
3. Let there be one Object holding the user's passwords i.e current password, new password and confirmed new password. this will be stored as a state variable in the component.
4. Let there be one state handler within the profile details component that accepts the state to change and the value to change it to. You can use a switch statement within and treat the functionality as needed. This should access the state variable only.
5. Likewise for the passwords component.
6. Let there be one universal state for editable. This state should be passed to each of the fields to make them inactive or active as needed. i.e. if editable is not selected, cursor != pointer, and values are not to be changed. only viewed.
7. On clicking save. The editable should be disabled and the local state should be dispatched to the redux state. otherwise, on clicking cancel this should be reverted to the initial state. 

Lets start from here and work our way out. I'm available if you have any questions.

Also @Eshy10 let's talk to samuel and look into implementing a map integration for the address field so that we are sure that the  addresses we are sending to the backend are correct. this will aid greatly with the errors we are presently seeing with sample data. 

cc: https://developers.google.com/maps/documentation/javascript/place-autocomplete

**Review by ObiTam — APPROVED** [review]

**Comment by ObiTam** [comment]
@Eshy10 Please review and give us feedback.

@Blossom1-chike Well done.

**Pull request merged**
